<?php
namespace MarketMeSuite\Phranken\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:34.
 */
class ArrayUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\ArrayUtils::BuildJoinedArray
     * @todo   Implement testBuildJoinedArray().
     */
    public function testBuildJoinedArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\ArrayUtils::ConstructFieldArray
     * @todo   Implement testConstructFieldArray().
     */
    public function testConstructFieldArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\ArrayUtils::FlattenArray
     * @todo   Implement testFlattenArray().
     */
    public function testFlattenArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
