<?php
namespace MarketMeSuite\Phranken\Commandline;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:33.
 */
class CLogTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CLog
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CLog;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::Log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::wrapInColor
     * @todo   Implement testWrapInColor().
     */
    public function testWrapInColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::applyColorMap
     * @todo   Implement testApplyColorMap().
     */
    public function testApplyColorMap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::getColors
     * @todo   Implement testGetColors().
     */
    public function testGetColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::setColors
     * @todo   Implement testSetColors().
     */
    public function testSetColors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::getColorMap
     * @todo   Implement testGetColorMap().
     */
    public function testGetColorMap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::setColorMap
     * @todo   Implement testSetColorMap().
     */
    public function testSetColorMap()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\CLog::suppressOutput
     * @todo   Implement testSuppressOutput().
     */
    public function testSuppressOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
