<?php
namespace MarketMeSuite\Phranken\Commandline;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 04:25:57.
 */
class ConsoleTableTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConsoleTable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConsoleTable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::getTableData
     * @todo   Implement testGetTableData().
     */
    public function testGetTableData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::drawTable
     * @todo   Implement testDrawTable().
     */
    public function testDrawTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::applyValueRenderer
     * @todo   Implement testApplyValueRenderer().
     */
    public function testApplyValueRenderer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::getColMaxWidth
     * @todo   Implement testGetColMaxWidth().
     */
    public function testGetColMaxWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::arrayGetMaxWidth
     * @todo   Implement testArrayGetMaxWidth().
     */
    public function testArrayGetMaxWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Commandline\ConsoleTable::getLongestRow
     * @todo   Implement testGetLongestRow().
     */
    public function testGetLongestRow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
