<?php
namespace MarketMeSuite\Phranken\Database\Object;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-04 at 15:21:40.
 */
class DbObjectDynamicTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DbObjectDynamic
     */
    protected $object;

    protected $data = array(
        '_id' => 'a_cool_id',
        'a_dynamic_key' => 'dynamic_value',
        'a_dynamic_key2' => 'dynamic_value2'
    );

    protected $dataSansMap = array(
        'a_dynamic_key' => 'dynamic_value',
        'a_dynamic_key2' => 'dynamic_value2'
    );

    protected $map = array(
        '_id' => 'id'
    );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass(
            'MarketMeSuite\\Phranken\\Database\\Object\\DbObjectDynamic'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Object\DbObjectDynamic::fromArray
     * @todo   Implement testFromArray().
     */
    public function testFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Object\DbObjectDynamic::parseDynamicProperties
     */
    public function testParseDynamicProperties()
    {
        $stub = $this->getMockForAbstractClass(
            'MarketMeSuite\\Phranken\\Database\\Object\\DbObjectDynamic'
        );

        $stub->setMap($this->map);
        $stub->parseDynamicProperties($this->data);

        $this->assertSame(
            $this->data['a_dynamic_key'],
            $stub->getDynamicProp('a_dynamic_key')
        );
    }


    /**
     * @covers MarketMeSuite\Phranken\Database\Object\DbObjectDynamic::getDynamicProp
     * @todo   Implement testGetDynamicProp().
     */
    public function testGetDynamicProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Object\DbObjectDynamic::setDynamicProp
     * @todo   Implement testSetDynamicProp().
     */
    public function testSetDynamicProp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Object\DbObjectDynamic::getDynamicProps
     */
    public function testGetDynamicProps()
    {
        $this->object->setMap($this->map);
        $this->object->fromArray($this->data);
        $props = $this->object->getDynamicprops();

        $this->assertSame(
            $this->dataSansMap,
            $props
        );
    }
}
