<?php
namespace MarketMeSuite\Phranken\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-14 at 20:49:26.
 */
class FileUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileUtils
     */
    protected $object;

    /**
     * An absolute *nix file path
     * @var string
     */
    protected $absolutePath = '/var/www/html';

    /**
     * A relative *nix file path
     * @var string
     */
    protected $relativePath = 'server/minecraft/mc01';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\FileUtils::isRelative
     */
    public function testIsRelative()
    {
        $this->assertSame(
            true,
            FileUtils::isRelative($this->relativePath),
            'function should return true for relative paths'
        );

        $this->assertSame(
            false,
            FileUtils::isRelative($this->absolutePath),
            'function should return false for absolute paths'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\FileUtils::isAbsolute
     */
    public function testIsAbsolute()
    {
        $this->assertSame(
            true,
            FileUtils::isAbsolute($this->absolutePath),
            'function should return true for absolute paths'
        );

        $this->assertSame(
            false,
            FileUtils::isAbsolute($this->relativePath),
            'function should return false for relative paths'
        );
    }
}
