<?php
namespace MarketMeSuite\Phranken\Database\Mongo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:34.
 */
class MongoConnectionManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MongoConnectionManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // @todo create some fake connection information
        // so we can create an instance
        //$this->object = new MongoConnectionManager;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\MongoConnectionManager::addDb
     * @todo   Implement testAddDb().
     */
    public function testAddDb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\MongoConnectionManager::configure
     * @todo   Implement testConfigure().
     */
    public function testConfigure()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\MongoConnectionManager::loadDb
     * @todo   Implement testLoadDb().
     */
    public function testLoadDb()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
