<?php
namespace MarketMeSuite\Phranken\Database\Mongo\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:34.
 */
class MongoUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MongoUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MongoUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::StringArrayToFieldsArray
     * @todo   Implement testStringArrayToFieldsArray().
     */
    public function testStringArrayToFieldsArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::ConstructInArray
     * @todo   Implement testConstructInArray().
     */
    public function testConstructInArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::ConstructAndArray
     * @todo   Implement testConstructAndArray().
     */
    public function testConstructAndArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::AddAndParams
     * @todo   Implement testAddAndParams().
     */
    public function testAddAndParams()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::GetArrayFromCursor
     * @todo   Implement testGetArrayFromCursor().
     */
    public function testGetArrayFromCursor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\Mongo\Util\MongoUtils::ArrayMembersToInt
     * @todo   Implement testArrayMembersToInt().
     */
    public function testArrayMembersToInt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
