<?php
namespace MarketMeSuite\Phranken\Database\MySql\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 04:15:23.
 */
class MysqlUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MysqlUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MysqlUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::MysqlUtils
     * @todo   Implement testMysqlUtils().
     */
    public function testMysqlUtils()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::ConstructInString
     * @todo   Implement testConstructInString().
     */
    public function testConstructInString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::ConstructInStringFromArray
     * @todo   Implement testConstructInStringFromArray().
     */
    public function testConstructInStringFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::ConstructFieldArray
     * @todo   Implement testConstructFieldArray().
     */
    public function testConstructFieldArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::GetFullArray
     * @todo   Implement testGetFullArray().
     */
    public function testGetFullArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::GetHTMLTable
     * @todo   Implement testGetHTMLTable().
     */
    public function testGetHTMLTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::DisplayMysqlResult
     * @todo   Implement testDisplayMysqlResult().
     */
    public function testDisplayMysqlResult()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::BuildFieldString
     * @todo   Implement testBuildFieldString().
     */
    public function testBuildFieldString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::BuildLikeQueryString
     * @todo   Implement testBuildLikeQueryString().
     */
    public function testBuildLikeQueryString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::BuildJoinedArray
     * @todo   Implement testBuildJoinedArray().
     */
    public function testBuildJoinedArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Database\MySql\Util\MysqlUtils::QueryAssoc
     * @todo   Implement testQueryAssoc().
     */
    public function testQueryAssoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
