<?php
namespace MarketMeSuite\Phranken\Util;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:34.
 */
class NetUtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NetUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NetUtils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Util\NetUtils::curl_get_contents
     * @todo   Implement testCurl_get_contents().
     */
    public function testCurl_get_contents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
