<?php
namespace MarketMeSuite\Phranken\Spl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 23:10:27.
 */
class SplClassLoaderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SplClassLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SplClassLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::setNamespaceSeparator
     * @todo   Implement testSetNamespaceSeparator().
     */
    public function testSetNamespaceSeparator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::getNamespaceSeparator
     * @todo   Implement testGetNamespaceSeparator().
     */
    public function testGetNamespaceSeparator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::setIncludePath
     * @todo   Implement testSetIncludePath().
     */
    public function testSetIncludePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::getIncludePath
     * @todo   Implement testGetIncludePath().
     */
    public function testGetIncludePath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::setFileExtension
     * @todo   Implement testSetFileExtension().
     */
    public function testSetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::getFileExtension
     * @todo   Implement testGetFileExtension().
     */
    public function testGetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::unregister
     * @todo   Implement testUnregister().
     */
    public function testUnregister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Spl\SplClassLoader::loadClass
     * @todo   Implement testLoadClass().
     */
    public function testLoadClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
