<?php
namespace MarketMeSuite\Phranken\Crypt;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-24 at 03:47:33.
 */
class UniqueIDGeneratorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UniqueIDGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UniqueIDGenerator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers MarketMeSuite\Phranken\Crypt\UniqueIDGenerator::GenerateID
     * @todo   Implement testGenerateID().
     */
    public function testGenerateID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Crypt\UniqueIDGenerator::GenerateUUID
     * @todo   Implement testGenerateUUID().
     */
    public function testGenerateUUID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MarketMeSuite\Phranken\Crypt\UniqueIDGenerator::GenerateShortID
     * @todo   Implement testGenerateShortID().
     */
    public function testGenerateShortID()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
